-- ============================================================================
-- Morgan Treasure Database Schema
-- Production-Ready MySQL 8.0+ / MariaDB Setup with Automated APY Management
-- ============================================================================

CREATE DATABASE IF NOT EXISTS `morgan_treasure` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `morgan_treasure`;

-- 1. Users Table (Core account balances, capping, rank, and downline totals)
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `wallet_address` VARCHAR(64) NOT NULL UNIQUE,
  `user_id` VARCHAR(20) NOT NULL UNIQUE,
  `sponsor_id` VARCHAR(20) NOT NULL DEFAULT 'MT-10024',
  `sponsor_address` VARCHAR(64) DEFAULT NULL,
  `nickname` VARCHAR(50) DEFAULT NULL,
  `active_package_id` VARCHAR(50) DEFAULT 'none',
  `active_package_name` VARCHAR(100) DEFAULT 'No Active Package',
  `total_staked_usdt` DECIMAL(18, 4) DEFAULT 0.0000,
  `available_balance_usdt` DECIMAL(18, 4) DEFAULT 0.0000,
  `total_withdrawn_usdt` DECIMAL(18, 4) DEFAULT 0.0000,
  `total_level_income_usdt` DECIMAL(18, 4) DEFAULT 0.0000,
  `total_direct_income_usdt` DECIMAL(18, 4) DEFAULT 0.0000,
  `total_roi_income_usdt` DECIMAL(18, 4) DEFAULT 0.0000,
  `total_royalty_income_usdt` DECIMAL(18, 4) DEFAULT 0.0000,
  `rank` VARCHAR(50) DEFAULT 'Treasure Explorer',
  `directs_count` INT DEFAULT 0,
  `active_directs_count` INT DEFAULT 0,
  `total_team_count` INT DEFAULT 0,
  `total_team_turnover_usdt` DECIMAL(18, 4) DEFAULT 0.0000,
  `max_capping_limit_usdt` DECIMAL(18, 4) DEFAULT 0.0000,
  `total_earning_towards_cap_usdt` DECIMAL(18, 4) DEFAULT 0.0000,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_sponsor_id` (`sponsor_id`),
  INDEX `idx_wallet` (`wallet_address`),
  INDEX `idx_staked` (`total_staked_usdt`)
) ENGINE=InnoDB;

-- 2. Staking Deposits Table
CREATE TABLE IF NOT EXISTS `deposits` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `wallet_address` VARCHAR(64) NOT NULL,
  `package_id` VARCHAR(50) NOT NULL,
  `amount_usdt` DECIMAL(18, 4) NOT NULL,
  `daily_roi_at_deposit` DECIMAL(5, 2) NOT NULL,
  `tx_hash` VARCHAR(80) NOT NULL UNIQUE,
  `status` ENUM('pending', 'confirmed', 'rejected') DEFAULT 'confirmed',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_deposit_wallet` (`wallet_address`),
  FOREIGN KEY (`wallet_address`) REFERENCES `users`(`wallet_address`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 3. Level Income Distribution Table (15 Tiers)
CREATE TABLE IF NOT EXISTS `level_income` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `beneficiary_wallet` VARCHAR(64) NOT NULL,
  `from_wallet` VARCHAR(64) NOT NULL,
  `level` INT NOT NULL,
  `commission_percent` DECIMAL(5, 2) NOT NULL,
  `amount_usdt` DECIMAL(18, 4) NOT NULL,
  `deposit_id` INT DEFAULT NULL,
  `tx_hash` VARCHAR(80) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_bene_wallet` (`beneficiary_wallet`),
  INDEX `idx_level` (`level`)
) ENGINE=InnoDB;

-- 4. Daily ROI Payouts Table (Generated by automated APY cron)
CREATE TABLE IF NOT EXISTS `daily_roi_payouts` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `wallet_address` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  `staked_amount_usdt` DECIMAL(18, 4) NOT NULL,
  `roi_rate_percent` DECIMAL(5, 2) NOT NULL,
  `gross_payout_usdt` DECIMAL(18, 4) NOT NULL,
  `credited_payout_usdt` DECIMAL(18, 4) NOT NULL,
  `remaining_cap_after` DECIMAL(18, 4) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_payout_wallet` (`wallet_address`),
  INDEX `idx_payout_date` (`created_at`)
) ENGINE=InnoDB;

-- 5. Withdrawals Table (With 5% Liquidity Retention Fee)
CREATE TABLE IF NOT EXISTS `withdrawals` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `wallet_address` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  `gross_amount_usdt` DECIMAL(18, 4) NOT NULL,
  `fee_amount_usdt` DECIMAL(18, 4) NOT NULL,
  `net_payout_usdt` DECIMAL(18, 4) NOT NULL,
  `tx_hash` VARCHAR(80) NOT NULL UNIQUE,
  `status` ENUM('pending', 'confirmed', 'failed') DEFAULT 'confirmed',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_with_wallet` (`wallet_address`),
  INDEX `idx_with_date` (`created_at`)
) ENGINE=InnoDB;

-- 6. Cron Execution Logs Table (Idempotency & Auditing)
CREATE TABLE IF NOT EXISTS `cron_logs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `job_name` VARCHAR(50) NOT NULL,
  `users_processed` INT DEFAULT 0,
  `total_payout_usdt` DECIMAL(18, 4) DEFAULT 0.0000,
  `roi_rate_percent` DECIMAL(5, 2) DEFAULT 0.00,
  `execution_seconds` DECIMAL(8, 4) DEFAULT 0.0000,
  `status` ENUM('completed', 'failed', 'running') DEFAULT 'completed',
  `error_message` TEXT DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_job_date` (`job_name`, `created_at`)
) ENGINE=InnoDB;

-- 7. Liquidity History & Dynamic ROI Pool Table
CREATE TABLE IF NOT EXISTS `liquidity_history` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `total_liquidity_usdt` DECIMAL(18, 4) NOT NULL,
  `available_reserve_usdt` DECIMAL(18, 4) NOT NULL,
  `utilization_rate` DECIMAL(5, 2) NOT NULL,
  `daily_roi_percent` DECIMAL(5, 2) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_liq_date` (`created_at`)
) ENGINE=InnoDB;

-- 8. MTG Token Orders Table
CREATE TABLE IF NOT EXISTS `token_orders` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `wallet_address` VARCHAR(64) NOT NULL,
  `token_amount` DECIMAL(18, 4) NOT NULL,
  `paid_amount` DECIMAL(18, 4) NOT NULL,
  `paid_currency` VARCHAR(10) NOT NULL,
  `tx_hash` VARCHAR(80) NOT NULL UNIQUE,
  `status` ENUM('completed', 'pending') DEFAULT 'completed',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Initial Seed Data: Root Genesis Account
INSERT INTO `users` (`wallet_address`, `user_id`, `sponsor_id`, `nickname`, `active_package_id`, `active_package_name`, `total_staked_usdt`, `max_capping_limit_usdt`, `rank`)
VALUES ('0x0000000000000000000000000000000000000001', 'MT-10024', 'MT-ROOT', 'Genesis Vault', 'treasure_5000', 'Imperial Treasure ($5,000)', 5000.00, 15000.00, 'Imperial Founder')
ON DUPLICATE KEY UPDATE `user_id` = `user_id`;

-- Initial Seed Data: Pool Liquidity Benchmark
INSERT INTO `liquidity_history` (`total_liquidity_usdt`, `available_reserve_usdt`, `utilization_rate`, `daily_roi_percent`)
VALUES (2480500.00, 1845492.00, 74.40, 0.84);
